# 第一层 版本，与docker版本对应，向下兼容。最新为3.9
version: "3.0"

# 第二层 服务
services:
  php-nginx:
    image: webdevops/php-nginx:7.4-alpine #镜像
    ports:
      - "2088:80"
    networks:
      - backend
    volumes:
      - s_php-nginx_config:/opt/docker/etc
      - s_php-nginx_www:/app
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:6.2.0-alpine
    ports:
      - "16379:6379"
    networks:
      - backend
      - frontend
    volumes:
      - s_redis_data:/data
    command: redis-server
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    networks:
      - backend
    volumes:
      - s_mysql_conf:/etc/mysql/conf.d
      - s_mysql_logs:/logs
      - s_mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
# 第三层 其他配置，如：网络、数据卷、全局配置
networks:
  frontend:
  backend:
volumes:
  s_php-nginx_config:
  s_php-nginx_www:
  s_redis_data:
  s_mysql_conf:
  s_mysql_logs:
  s_mysql_data:
